services:
  configsrv:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: configsrv
    command: --configsvr --replSet configReplSet
    ports:
      - 27019:27019

  shard1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1
    command: --shardsvr --replSet shard1ReplSet --port 27018
    ports:
      - 27018:27018

  shard2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2
    command: --shardsvr --replSet shard2ReplSet --port 27020
    ports:
      - 27020:27020

  mongos:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongos
    command: mongos --configdb configReplSet/configsrv:27019 --port 27017
    ports:
      - 27017:27017
    depends_on:
      - configsrv
      - shard1
      - shard2
    volumes:
      - mongos_data_container:/data/db

  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos"
      MONGODB_DATABASE_NAME: "db"

volumes:
  mongos_data_container:
